import 'package:democracy/user/models/user.dart';

User user1 = User(
  id: 1,
  username: 'Jamoh007',
  name: 'James Mutahi',
  email: 'mutahijames0@gmail.com',
  isActive: true,
  status: '',
  dateJoined: '1944-06-06 02:00:00.000' as DateTime,
  image: '',
  coverPhoto: '',
  following: 2,
  followers: 0,
  muted: [],
  blocked: [],
  isMuted: false,
  isBlocked: false,
  hasBlocked: false,
  isFollowed: false,
);

User user2 = User(
  id: 2,
  username: 'GIJoe',
  name: 'g g',
  email: 'g@g.com',
  isActive: true,
  status: '',
  dateJoined: '1944-06-06 02:00:00.000' as DateTime,
  image: '',
  coverPhoto: '',
  following: 2,
  followers: 0,
  muted: [],
  blocked: [],
  isMuted: false,
  isBlocked: false,
  hasBlocked: false,
  isFollowed: false,
);
