// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:democracy/chat/models/chat.dart';
import 'package:democracy/chat/models/message.dart';
import 'package:democracy/post/models/draft_post.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatAdapter());
    registerAdapter(DraftPostAdapter());
    registerAdapter(MessageAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatAdapter());
    registerAdapter(DraftPostAdapter());
    registerAdapter(MessageAdapter());
  }
}
