// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'chat/models/chat.dart';
import 'chat/models/message.dart';
import 'post/models/draft_post.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4508093392900912733),
    name: 'Chat',
    lastPropertyId: const obx_int.IdUid(4, 7795444535218738920),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5723960947784621580),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4628224136409872408),
        name: 'usersJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 187529252864569788),
        name: 'unreadMessages',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7795444535218738920),
        name: 'lastMessageId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6178847164186925076),
        relationField: 'lastMessage',
        relationTarget: 'Message',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 2495467324350740979),
        name: 'messages',
        targetId: const obx_int.IdUid(3, 360974746986061726),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5363977148625922115),
    name: 'DraftPost',
    lastPropertyId: const obx_int.IdUid(15, 948205295835912004),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1184097624306350941),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1970381774403629254),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5739811656828620113),
        name: 'filePaths',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8493938067958260025),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6496495314297795879),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4044838006271308045),
        name: 'locationJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6977655167073971949),
        name: 'replyToJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8878305876661353910),
        name: 'repostOfJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 704009229005157330),
        name: 'communityNoteOfJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2276427656469037958),
        name: 'ballotJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6630013591171368454),
        name: 'surveyJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7331794809423639780),
        name: 'petitionJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4613018214046083354),
        name: 'meetingJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3328815096339374325),
        name: 'sectionJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 948205295835912004),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 360974746986061726),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(21, 7204170551757178761),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5222149983654943280),
        name: 'targetId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 717800694345432413),
        name: 'id',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5953340159521476473),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5944254126816884648),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2285450464718918607),
        name: 'isEdited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7164841083985417019),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 722618201613990254),
        name: 'postRequired',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6190321578982983887),
        name: 'patchRequired',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8309295689238708592),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1472424613154098738),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4286773945632654789),
        name: 'authorJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4291386024835224102),
        name: 'locationJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 918455753003201513),
        name: 'postJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6727627825323363504),
        name: 'ballotJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7876522097113120105),
        name: 'surveyJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2231236850551063636),
        name: 'petitionJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 291135108683617933),
        name: 'meetingJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3750721680211431668),
        name: 'sectionJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 537896190871936585),
        name: 'assetsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 9120627803404601846),
        name: 'uploadsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7204170551757178761),
        name: 'chatId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1953878758056447447),
        relationField: 'chat',
        relationTarget: 'Chat',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 360974746986061726),
    lastIndexId: const obx_int.IdUid(2, 1953878758056447447),
    lastRelationId: const obx_int.IdUid(1, 2495467324350740979),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Chat: obx_int.EntityDefinition<Chat>(
      model: _entities[0],
      toOneRelations: (Chat object) => [object.lastMessage],
      toManyRelations: (Chat object) => {
        obx_int.RelInfo<Chat>.toMany(1, object.id): object.messages,
      },
      getId: (Chat object) => object.id,
      setId: (Chat object, int id) {
        object.id = id;
      },
      objectToFB: (Chat object, fb.Builder fbb) {
        final usersJsonOffset = object.usersJson == null
            ? null
            : fbb.writeString(object.usersJson!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usersJsonOffset);
        fbb.addInt64(2, object.unreadMessages);
        fbb.addInt64(3, object.lastMessage.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final unreadMessagesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = Chat(id: idParam, unreadMessages: unreadMessagesParam)
          ..usersJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6);
        object.lastMessage.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.lastMessage.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Chat>(
          object.messages,
          store,
          obx_int.RelInfo<Chat>.toMany(1, object.id),
        );
        return object;
      },
    ),
    DraftPost: obx_int.EntityDefinition<DraftPost>(
      model: _entities[1],
      toOneRelations: (DraftPost object) => [],
      toManyRelations: (DraftPost object) => {},
      getId: (DraftPost object) => object.id,
      setId: (DraftPost object, int id) {
        object.id = id;
      },
      objectToFB: (DraftPost object, fb.Builder fbb) {
        final bodyOffset = fbb.writeString(object.body);
        final filePathsOffset = fbb.writeList(
          object.filePaths.map(fbb.writeString).toList(growable: false),
        );
        final locationJsonOffset = object.locationJson == null
            ? null
            : fbb.writeString(object.locationJson!);
        final replyToJsonOffset = object.replyToJson == null
            ? null
            : fbb.writeString(object.replyToJson!);
        final repostOfJsonOffset = object.repostOfJson == null
            ? null
            : fbb.writeString(object.repostOfJson!);
        final communityNoteOfJsonOffset = object.communityNoteOfJson == null
            ? null
            : fbb.writeString(object.communityNoteOfJson!);
        final ballotJsonOffset = object.ballotJson == null
            ? null
            : fbb.writeString(object.ballotJson!);
        final surveyJsonOffset = object.surveyJson == null
            ? null
            : fbb.writeString(object.surveyJson!);
        final petitionJsonOffset = object.petitionJson == null
            ? null
            : fbb.writeString(object.petitionJson!);
        final meetingJsonOffset = object.meetingJson == null
            ? null
            : fbb.writeString(object.meetingJson!);
        final sectionJsonOffset = object.sectionJson == null
            ? null
            : fbb.writeString(object.sectionJson!);
        final tagsJsonOffset = object.tagsJson == null
            ? null
            : fbb.writeString(object.tagsJson!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, bodyOffset);
        fbb.addOffset(2, filePathsOffset);
        fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(5, locationJsonOffset);
        fbb.addOffset(6, replyToJsonOffset);
        fbb.addOffset(7, repostOfJsonOffset);
        fbb.addOffset(8, communityNoteOfJsonOffset);
        fbb.addOffset(9, ballotJsonOffset);
        fbb.addOffset(10, surveyJsonOffset);
        fbb.addOffset(11, petitionJsonOffset);
        fbb.addOffset(12, meetingJsonOffset);
        fbb.addOffset(13, sectionJsonOffset);
        fbb.addOffset(14, tagsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object =
            DraftPost(
                id: idParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
              )
              ..body = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..filePaths = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 8, [])
              ..locationJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 14)
              ..replyToJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 16)
              ..repostOfJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 18)
              ..communityNoteOfJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 20)
              ..ballotJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 22)
              ..surveyJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 24)
              ..petitionJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 26)
              ..meetingJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 28)
              ..sectionJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 30)
              ..tagsJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 32);

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[2],
      toOneRelations: (Message object) => [object.chat],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.targetId,
      setId: (Message object, int id) {
        object.targetId = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final authorJsonOffset = object.authorJson == null
            ? null
            : fbb.writeString(object.authorJson!);
        final locationJsonOffset = object.locationJson == null
            ? null
            : fbb.writeString(object.locationJson!);
        final postJsonOffset = object.postJson == null
            ? null
            : fbb.writeString(object.postJson!);
        final ballotJsonOffset = object.ballotJson == null
            ? null
            : fbb.writeString(object.ballotJson!);
        final surveyJsonOffset = object.surveyJson == null
            ? null
            : fbb.writeString(object.surveyJson!);
        final petitionJsonOffset = object.petitionJson == null
            ? null
            : fbb.writeString(object.petitionJson!);
        final meetingJsonOffset = object.meetingJson == null
            ? null
            : fbb.writeString(object.meetingJson!);
        final sectionJsonOffset = object.sectionJson == null
            ? null
            : fbb.writeString(object.sectionJson!);
        final assetsJsonOffset = object.assetsJson == null
            ? null
            : fbb.writeString(object.assetsJson!);
        final uploadsJsonOffset = object.uploadsJson == null
            ? null
            : fbb.writeString(object.uploadsJson!);
        fbb.startTable(22);
        fbb.addInt64(0, object.targetId);
        fbb.addInt64(1, object.id);
        fbb.addOffset(2, textOffset);
        fbb.addBool(3, object.isRead);
        fbb.addBool(4, object.isEdited);
        fbb.addBool(5, object.isDeleted);
        fbb.addBool(6, object.postRequired);
        fbb.addBool(7, object.patchRequired);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(10, authorJsonOffset);
        fbb.addOffset(11, locationJsonOffset);
        fbb.addOffset(12, postJsonOffset);
        fbb.addOffset(13, ballotJsonOffset);
        fbb.addOffset(14, surveyJsonOffset);
        fbb.addOffset(15, petitionJsonOffset);
        fbb.addOffset(16, meetingJsonOffset);
        fbb.addOffset(17, sectionJsonOffset);
        fbb.addOffset(18, assetsJsonOffset);
        fbb.addOffset(19, uploadsJsonOffset);
        fbb.addInt64(20, object.chat.targetId);
        fbb.finish(fbb.endTable());
        return object.targetId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final targetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isEditedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final postRequiredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final patchRequiredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object =
            Message(
                targetId: targetIdParam,
                id: idParam,
                text: textParam,
                isRead: isReadParam,
                isEdited: isEditedParam,
                isDeleted: isDeletedParam,
                postRequired: postRequiredParam,
                patchRequired: patchRequiredParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
              )
              ..authorJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 24)
              ..locationJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 26)
              ..postJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 28)
              ..ballotJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 30)
              ..surveyJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 32)
              ..petitionJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 34)
              ..meetingJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 36)
              ..sectionJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 38)
              ..assetsJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 40)
              ..uploadsJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 42);
        object.chat.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        object.chat.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chat] entity fields to define ObjectBox queries.
class Chat_ {
  /// See [Chat.id].
  static final id = obx.QueryIntegerProperty<Chat>(_entities[0].properties[0]);

  /// See [Chat.usersJson].
  static final usersJson = obx.QueryStringProperty<Chat>(
    _entities[0].properties[1],
  );

  /// See [Chat.unreadMessages].
  static final unreadMessages = obx.QueryIntegerProperty<Chat>(
    _entities[0].properties[2],
  );

  /// See [Chat.lastMessage].
  static final lastMessage = obx.QueryRelationToOne<Chat, Message>(
    _entities[0].properties[3],
  );

  /// see [Chat.messages]
  static final messages = obx.QueryRelationToMany<Chat, Message>(
    _entities[0].relations[0],
  );
}

/// [DraftPost] entity fields to define ObjectBox queries.
class DraftPost_ {
  /// See [DraftPost.id].
  static final id = obx.QueryIntegerProperty<DraftPost>(
    _entities[1].properties[0],
  );

  /// See [DraftPost.body].
  static final body = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[1],
  );

  /// See [DraftPost.filePaths].
  static final filePaths = obx.QueryStringVectorProperty<DraftPost>(
    _entities[1].properties[2],
  );

  /// See [DraftPost.updatedAt].
  static final updatedAt = obx.QueryDateProperty<DraftPost>(
    _entities[1].properties[3],
  );

  /// See [DraftPost.createdAt].
  static final createdAt = obx.QueryDateProperty<DraftPost>(
    _entities[1].properties[4],
  );

  /// See [DraftPost.locationJson].
  static final locationJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[5],
  );

  /// See [DraftPost.replyToJson].
  static final replyToJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[6],
  );

  /// See [DraftPost.repostOfJson].
  static final repostOfJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[7],
  );

  /// See [DraftPost.communityNoteOfJson].
  static final communityNoteOfJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[8],
  );

  /// See [DraftPost.ballotJson].
  static final ballotJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[9],
  );

  /// See [DraftPost.surveyJson].
  static final surveyJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[10],
  );

  /// See [DraftPost.petitionJson].
  static final petitionJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[11],
  );

  /// See [DraftPost.meetingJson].
  static final meetingJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[12],
  );

  /// See [DraftPost.sectionJson].
  static final sectionJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[13],
  );

  /// See [DraftPost.tagsJson].
  static final tagsJson = obx.QueryStringProperty<DraftPost>(
    _entities[1].properties[14],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.targetId].
  static final targetId = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[0],
  );

  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[1],
  );

  /// See [Message.text].
  static final text = obx.QueryStringProperty<Message>(
    _entities[2].properties[2],
  );

  /// See [Message.isRead].
  static final isRead = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[3],
  );

  /// See [Message.isEdited].
  static final isEdited = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[4],
  );

  /// See [Message.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[5],
  );

  /// See [Message.postRequired].
  static final postRequired = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[6],
  );

  /// See [Message.patchRequired].
  static final patchRequired = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[7],
  );

  /// See [Message.createdAt].
  static final createdAt = obx.QueryDateProperty<Message>(
    _entities[2].properties[8],
  );

  /// See [Message.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Message>(
    _entities[2].properties[9],
  );

  /// See [Message.authorJson].
  static final authorJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[10],
  );

  /// See [Message.locationJson].
  static final locationJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[11],
  );

  /// See [Message.postJson].
  static final postJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[12],
  );

  /// See [Message.ballotJson].
  static final ballotJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[13],
  );

  /// See [Message.surveyJson].
  static final surveyJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[14],
  );

  /// See [Message.petitionJson].
  static final petitionJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[15],
  );

  /// See [Message.meetingJson].
  static final meetingJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[16],
  );

  /// See [Message.sectionJson].
  static final sectionJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[17],
  );

  /// See [Message.assetsJson].
  static final assetsJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[18],
  );

  /// See [Message.uploadsJson].
  static final uploadsJson = obx.QueryStringProperty<Message>(
    _entities[2].properties[19],
  );

  /// See [Message.chat].
  static final chat = obx.QueryRelationToOne<Message, Chat>(
    _entities[2].properties[20],
  );
}
